#!/usr/bin/env python3
"""Generate star_map_data.h from the Hipparcos catalogue + Stellarium constellation lines.

Uses astroquery to fetch the Hipparcos catalogue from Vizier, and loads
constellation stick figure data from Stellarium's index.json (modern sky culture).

Usage:
    .venv/bin/python generate.py [--mag-limit 5.0] [--output ../../pi/src/star_map_data.h]
    .venv/bin/python generate.py --plot Ori Sco
"""

import argparse
import json
import os
import sys
import numpy as np


def load_constellations(json_path):
    """Load constellation data from Stellarium index.json.

    The JSON format uses polylines: each entry in 'lines' is a chain of HIP IDs
    like [h1, h2, h3] meaning h1-h2 and h2-h3.

    Returns {abbr: [(hip1, hip2), ...]}
    """
    with open(json_path) as f:
        data = json.load(f)

    constellations = {}
    for entry in data['constellations']:
        # id is like "CON modern Ori"
        abbr = entry['id'].split()[-1]
        segments = []
        for polyline in entry['lines']:
            for i in range(len(polyline) - 1):
                segments.append((polyline[i], polyline[i + 1]))
        constellations[abbr] = segments

    return constellations


def fetch_hipparcos(mag_limit):
    """Fetch Hipparcos catalogue from Vizier up to given magnitude."""
    from astroquery.vizier import Vizier

    print(f"Fetching Hipparcos stars with Vmag < {mag_limit} from Vizier...")
    v = Vizier(columns=['HIP', 'RAICRS', 'DEICRS', 'Vmag'],
               row_limit=-1)
    result = v.query_constraints(catalog='I/239/hip_main', Vmag=f'<{mag_limit}')
    if not result:
        print("ERROR: No results from Vizier query", file=sys.stderr)
        sys.exit(1)

    hip = result[0]
    stars = {}  # hip_id -> (ra_rad, dec_rad, vmag)
    for row in hip:
        try:
            hip_id = int(row['HIP'])
            ra_deg = float(row['RAICRS'])
            dec_deg = float(row['DEICRS'])
            mag = float(row['Vmag'])
            if not np.isnan(ra_deg) and not np.isnan(dec_deg) and not np.isnan(mag):
                stars[hip_id] = (np.radians(ra_deg), np.radians(dec_deg), mag)
        except (ValueError, KeyError):
            continue

    print(f"  Got {len(stars)} stars")
    return stars


def ensure_constellation_stars(stars, constellations, mag_limit_extra=7.0):
    """Make sure all stars referenced by constellation lines exist in the catalogue.

    Some constellation endpoint stars may be fainter than the main mag limit.
    Fetch them individually if needed.
    """
    needed_hips = set()
    for abbr, segments in constellations.items():
        for h1, h2 in segments:
            if h1 not in stars:
                needed_hips.add(h1)
            if h2 not in stars:
                needed_hips.add(h2)

    if not needed_hips:
        return stars

    print(f"  {len(needed_hips)} constellation stars missing, fetching extras...")
    from astroquery.vizier import Vizier

    v = Vizier(columns=['HIP', 'RAICRS', 'DEICRS', 'Vmag'], row_limit=-1)
    result = v.query_constraints(catalog='I/239/hip_main', Vmag=f'<{mag_limit_extra}')
    if result:
        for row in result[0]:
            try:
                hip_id = int(row['HIP'])
                if hip_id in needed_hips and hip_id not in stars:
                    ra_deg = float(row['RAICRS'])
                    dec_deg = float(row['DEICRS'])
                    mag = float(row['Vmag'])
                    if not np.isnan(ra_deg) and not np.isnan(dec_deg) and not np.isnan(mag):
                        stars[hip_id] = (np.radians(ra_deg), np.radians(dec_deg), mag)
            except (ValueError, KeyError):
                continue

    still_missing = needed_hips - set(stars.keys())
    if still_missing:
        print(f"  WARNING: {len(still_missing)} constellation stars still missing: {still_missing}",
              file=sys.stderr)

    return stars


def generate_header(stars_dict, constellations, output_path):
    """Generate star_map_data.h from star dict and constellation data."""

    # Assign indices to stars, sorted by HIP ID for reproducibility
    hip_ids = sorted(stars_dict.keys())
    hip_to_idx = {hip: i for i, hip in enumerate(hip_ids)}

    stars = [(hip, *stars_dict[hip]) for hip in hip_ids]  # (hip, ra, dec, mag)

    # Resolve constellation lines to index pairs
    lines = []
    for abbr, segments in sorted(constellations.items()):
        for h1, h2 in segments:
            if h1 in hip_to_idx and h2 in hip_to_idx:
                lines.append((hip_to_idx[h1], hip_to_idx[h2]))

    num_stars = len(stars)
    num_lines = len(lines)

    with open(output_path, 'w') as f:
        f.write("// Auto-generated by tools/star_catalog/generate.py\n")
        f.write("// Source: Hipparcos catalogue (ESA, 1997) via Vizier\n")
        f.write("// Constellation lines: Stellarium modern sky culture\n")
        f.write("// Do not edit manually\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")

        f.write(f"static constexpr int STAR_MAP_NUM_STARS = {num_stars};\n")
        f.write(f"static constexpr int STAR_MAP_NUM_LINES = {num_lines};\n\n")

        f.write("// Star right ascension in radians\n")
        f.write("static constexpr float STAR_MAP_RA[] = {\n")
        for hip, ra, dec, mag in stars:
            f.write(f"    {ra:.6f}f,\n")
        f.write("};\n\n")

        f.write("// Star declination in radians\n")
        f.write("static constexpr float STAR_MAP_DEC[] = {\n")
        for hip, ra, dec, mag in stars:
            f.write(f"    {dec:.6f}f,\n")
        f.write("};\n\n")

        f.write("// Visual magnitude * 10 (e.g., 15 = mag 1.5)\n")
        f.write("static constexpr int8_t STAR_MAP_MAG10[] = {\n")
        for hip, ra, dec, mag in stars:
            m10 = int(round(mag * 10))
            m10 = max(-128, min(127, m10))
            f.write(f"    {m10},\n")
        f.write("};\n\n")

        f.write("// Constellation stick figure lines (pairs of star indices)\n")
        f.write("static constexpr uint16_t STAR_MAP_LINES[][2] = {\n")
        for i1, i2 in lines:
            f.write(f"    {{{i1}, {i2}}},\n")
        f.write("};\n")

    print(f"Generated {output_path}:")
    print(f"  {num_stars} stars, {num_lines} constellation lines")

    mags = [mag for _, _, _, mag in stars]
    print(f"  Magnitude range: {min(mags):.2f} to {max(mags):.2f}")
    bright = sum(1 for m in mags if m < 3.5)
    print(f"  Bright stars (mag < 3.5): {bright}")
    print(f"  Dim stars (mag >= 3.5): {num_stars - bright}")


def plot_constellation(stars_dict, constellations, names, fov_deg=50.0,
                       center_ra_deg=None, center_dec_deg=None, mag_limit=6.0):
    """Plot one or more constellations with gnomonic projection using matplotlib."""
    import matplotlib.pyplot as plt

    # Collect all HIP IDs involved in the requested constellations
    involved_hips = set()
    segments = []
    for name in names:
        if name not in constellations:
            print(f"Warning: constellation '{name}' not found", file=sys.stderr)
            print(f"  Available: {sorted(constellations.keys())}", file=sys.stderr)
            continue
        for h1, h2 in constellations[name]:
            involved_hips.add(h1)
            involved_hips.add(h2)
            segments.append((h1, h2))

    if not involved_hips:
        return

    # Auto-center on the mean position of constellation stars
    if center_ra_deg is None or center_dec_deg is None:
        ras, decs = [], []
        for hip in involved_hips:
            if hip in stars_dict:
                ra, dec, _ = stars_dict[hip]
                ras.append(ra)
                decs.append(dec)
        if not ras:
            print("No stars found for centering", file=sys.stderr)
            return
        mx = np.mean([np.cos(d) * np.cos(r) for r, d in zip(ras, decs)])
        my = np.mean([np.cos(d) * np.sin(r) for r, d in zip(ras, decs)])
        mz = np.mean([np.sin(d) for _, d in zip(ras, decs)])
        center_ra = np.arctan2(my, mx)
        center_dec = np.arcsin(mz / np.sqrt(mx**2 + my**2 + mz**2))
    else:
        center_ra = np.radians(center_ra_deg)
        center_dec = np.radians(center_dec_deg)

    fov_rad = np.radians(fov_deg)
    scale = 1.0 / (2.0 * np.tan(fov_rad / 2.0))

    def project(ra, dec):
        dra = ra - center_ra
        sin_d, cos_d = np.sin(dec), np.cos(dec)
        sin_d0, cos_d0 = np.sin(center_dec), np.cos(center_dec)
        cos_dra, sin_dra = np.cos(dra), np.sin(dra)
        cos_c = sin_d0 * sin_d + cos_d0 * cos_d * cos_dra
        if cos_c <= 0.01:
            return None, None
        x = -(cos_d * sin_dra) / cos_c * scale
        y = (cos_d0 * sin_d - sin_d0 * cos_d * cos_dra) / cos_c * scale
        return x, y

    fig, ax = plt.subplots(1, 1, figsize=(10, 10), facecolor='black')
    ax.set_facecolor('black')
    ax.set_xlim(-0.55, 0.55)
    ax.set_ylim(-0.55, 0.55)
    ax.set_aspect('equal')
    ax.set_title(', '.join(names), color='white', fontsize=16)
    ax.tick_params(colors='grey')
    for spine in ax.spines.values():
        spine.set_color('grey')

    # Plot all stars in the field
    for hip, (ra, dec, mag) in stars_dict.items():
        if mag > mag_limit:
            continue
        x, y = project(ra, dec)
        if x is None or abs(x) > 0.55 or abs(y) > 0.55:
            continue
        size = max(0.5, 6.0 - mag) ** 2 * 0.5
        color = 'white' if mag < 3.5 else '#888888'
        ax.plot(x, y, '.', color=color, markersize=size)

        if hip in involved_hips and mag < 5.5:
            ax.annotate(f'{hip}', (x, y), color='#44aaff', fontsize=7,
                        xytext=(4, 4), textcoords='offset points')

    # Draw constellation lines
    for h1, h2 in segments:
        if h1 not in stars_dict or h2 not in stars_dict:
            missing = []
            if h1 not in stars_dict: missing.append(h1)
            if h2 not in stars_dict: missing.append(h2)
            print(f"  Missing star(s) for line: {missing}", file=sys.stderr)
            continue
        ra1, dec1, _ = stars_dict[h1]
        ra2, dec2, _ = stars_dict[h2]
        x1, y1 = project(ra1, dec1)
        x2, y2 = project(ra2, dec2)
        if x1 is None or x2 is None:
            continue
        ax.plot([x1, x2], [y1, y2], '-', color='#336699', linewidth=1.0, alpha=0.7)

    ax.plot(0, 0, '+', color='red', markersize=10, markeredgewidth=0.5)

    plt.tight_layout()
    plt.show()


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_json = os.path.join(script_dir, 'index.json')
    default_output = os.path.join(script_dir, '..', '..', 'pi', 'src', 'star_map_data.h')

    parser = argparse.ArgumentParser(description='Generate star_map_data.h from Hipparcos')
    parser.add_argument('--mag-limit', type=float, default=5.0,
                        help='Magnitude limit for catalogue stars (default: 5.0)')
    parser.add_argument('--output', type=str, default=default_output,
                        help='Output header file path')
    parser.add_argument('--constellations', type=str, default=default_json,
                        help='Stellarium index.json path (default: index.json in script dir)')
    parser.add_argument('--plot', type=str, nargs='+', metavar='ABBR',
                        help='Plot constellation(s) instead of generating header '
                             '(e.g. --plot Ori Sco)')
    parser.add_argument('--fov', type=float, default=50.0,
                        help='Plot FOV in degrees (default: 50)')
    args = parser.parse_args()

    constellations = load_constellations(args.constellations)
    total_segments = sum(len(s) for s in constellations.values())
    print(f"Loaded {len(constellations)} constellations, {total_segments} line segments "
          f"from {os.path.basename(args.constellations)}")

    stars = fetch_hipparcos(args.mag_limit)
    stars = ensure_constellation_stars(stars, constellations)

    if args.plot:
        plot_constellation(stars, constellations, args.plot,
                           fov_deg=args.fov, mag_limit=args.mag_limit)
    else:
        generate_header(stars, constellations, args.output)


if __name__ == "__main__":
    main()
